# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounsilSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('number', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=255)),
                ('voting_result_file', models.CharField(max_length=255)),
                ('counsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='voting.Counsil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('counsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputies', to='voting.Counsil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('voting_result', models.CharField(max_length=255)),
                ('resolution', models.CharField(max_length=255)),
                ('voting_number', models.CharField(max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='voting.CounsilSession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LawVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vote', models.CharField(max_length=255)),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='law_voting', to='voting.Deputy')),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_voting', to='voting.Law')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
